global using Microsoft.EntityFrameworkCore;
global using Microsoft.AspNetCore.Identity;
global using Restaurant.DAL.Entities;
global using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
global using System.ComponentModel.DataAnnotations;
global using Restaurant.DAL.Enum;
global using Restaurant.DAL.Database;
global using System.Linq.Expressions;
global using Restaurant.DAL.Repo.Abstraction;
