global using System.ComponentModel.DataAnnotations;
global using Restaurant.DAL.Entities;
global using AutoMapper;
global using Restaurant.BLL.Service.Abstraction;
global using Restaurant.DAL.Repo.Abstraction;
global using Restaurant.BLL.ModelVMAccountVM;
global using Restaurant.DAL.Enum;
global using Microsoft.Extensions.Configuration;
global using System.Net;
global using System.Net.Mail;
global using Restaurant.BLL.ModelVMProfileVM;
global using Microsoft.AspNetCore.Authentication;
global using Microsoft.AspNetCore.Identity;
global using Restaurant.BLL.Abstraction;
global using Restaurant.DAL.Database;
global using Restaurant.BLL.Services.Interfaces;
global using ResetPasswordVM = Restaurant.BLL.ModelVMProfileVM.ResetPasswordVM;
global using Restaurant.BLL.ModelVMOrderItem;
global using Restaurant.BLL.ModelVMOrder;
global using Restaurant.BLL.ModelVMPromoCode;
global using Restaurant.BLL.Model_VM.Booking;
global using Restaurant.BLL.Model_VM.EmailNotification;
global using Restaurant.BLL.Model_VM.Feedback;
global using Restaurant.BLL.Model_VM.Table;
global using Microsoft.EntityFrameworkCore;

global using Restaurant.BLL.Model_VM.Cart;
global using Restaurant.BLL.ModelVM.ProductVM;